[build-system]
requires = ["setuptools>=70.0"]
build-backend = "setuptools.build_meta"

[project]
name = "comfyui-flame-face-map"
version = "0.0.1"
description = "ComfyUI custom node to generate 3D face normal maps, depth maps, and masks using the FLAME model"
authors = [
  {name = "Swayem Kandangwa", email = "sk5g22@soton.ac.uk"}
]
readme = "README.md"
license = {text = "GNU General Public License v3"}
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Multimedia :: Graphics :: 3D Modeling",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "numpy",
    "torch",
    "smplx",
]

[project.optional-dependencies]
dev = [
    "bump-my-version",
    "mypy",  # linting
    "pre-commit", # runs linting on commit
    "ruff",  # linting
]

[project.urls]
Repository = "https://github.com/hype1356/ComfyUI-FLAME-face-map"
BugTracker = "https://github.com/hype1356/ComfyUI-FLAME-face-map/issues"

[tool.comfy]
PublisherId = "hype1356"
DisplayName = "ComfyUI FLAME Face Map"
Icon = ""
Tags = ["flame", "3d", "face", "normal-map", "depth-map", "mask"]
Repository = "https://github.com/hype1356/ComfyUI-FLAME-face-map"

includes = []

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"flame_face_map" = ["*.pkl"]
"*" = ["*.*"]

[tool.mypy]
files = "."

# Use strict defaults
strict = true
warn_unreachable = true
warn_no_return = true

[tool.ruff]
line-length = 140
src = ["src"]
target-version = "py310"


# Add rules to ban exec/eval
[tool.ruff.lint]
select = [
    "S102",  # exec-builtin
    "S307",  # eval-used
    "W293",
    "F",  # Pyflakes rules
]

[tool.ruff.lint.flake8-quotes]
inline-quotes = "double"

